package com.jkxy.entity;
// Generated 2016-7-28 12:49:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * Poets generated by hbm2java
 */
public class Poets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<Poetries> poetries;

	public Poets() {
	}

	public Poets(String name, Date createdAt, Date updatedAt) {
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Poetries> getPoetries() {
		return poetries;
	}

	public void setPoetries(Set<Poetries> poetries) {
		this.poetries = poetries;
	}

}
