package com.vipmanage.model;
// Generated 2016-8-19 17:54:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Consume generated by hbm2java
 */
@Entity
@Table(name = "consume")
public class Consume implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer consumeId;

	// 多对一配置
	@ManyToOne
	@JoinColumn(name = "commodityId", referencedColumnName = "commodityId")
	private Commodity commodity;

	// 多对一 配置
	@ManyToOne
	@JoinColumn(name = "vipid", referencedColumnName = "vipId")
	private Vip vip;
	private String name;
	private String commodityName;
	private BigDecimal price;
	private BigDecimal practicePrice;
	// 保存一位小数点的价格和实收金额
	private BigDecimal formatPrice;
	private BigDecimal formatPracticePrice;

	public Consume() {
	}

	public Consume(Commodity commodity, Vip vip, String name, String commodityName, BigDecimal price,
			BigDecimal practicePrice) {
		this.commodity = commodity;
		this.vip = vip;
		this.name = name;
		this.commodityName = commodityName;
		this.price = price;
		this.practicePrice = practicePrice;
	}

	public Integer getConsumeId() {
		return this.consumeId;
	}

	public void setConsumeId(Integer consumeId) {
		this.consumeId = consumeId;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public Vip getVip() {
		return this.vip;
	}

	public void setVip(Vip vip) {
		this.vip = vip;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getPracticePrice() {
		return this.practicePrice;
	}

	public BigDecimal getFormatPrice() {
		return this.price.setScale(1, BigDecimal.ROUND_HALF_UP);
	}

	public void setFormatPrice(BigDecimal formatPrice) {
		this.formatPrice = formatPrice;
	}

	public BigDecimal getFormatPracticePrice() {
		return this.practicePrice.setScale(1, BigDecimal.ROUND_HALF_UP);
	}

	public void setFormatPracticePrice(BigDecimal formatPracticePrice) {
		this.formatPracticePrice = formatPracticePrice;
	}

}
