package com.vipmanage.model;
// Generated 2016-8-19 17:54:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	@Id
	private String username;
	private String password;
	private Integer quanxian;

	public User() {
	}

	public User(String username) {
		this.username = username;
	}

	public User(String username, String password, Integer quanxian) {
		this.username = username;
		this.password = password;
		this.quanxian = quanxian;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getQuanxian() {
		return this.quanxian;
	}

	public void setQuanxian(Integer quanxian) {
		this.quanxian = quanxian;
	}

}
