package com.vipmanage.model;
// Generated 2016-8-19 17:54:14 by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vip generated by hbm2java
 */
@Entity
@Table(name = "vip")
public class Vip implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer vipId;
	private Date joinTime;
	private String formatJoinTime;
	private String name;
	private Integer age;
	private String profession;
	// 以多端为关系维护端，级联用ALL
	@OneToMany(mappedBy = "vip", cascade = (CascadeType.ALL))
	private Set<Consume> consumes = new HashSet<Consume>();

	public Vip() {
	}

	public Vip(Date joinTime, String name, Integer age, String profession) {
		this.joinTime = joinTime;
		this.name = name;
		this.age = age;
		this.profession = profession;
	}

	public Integer getVipId() {
		return this.vipId;
	}

	public void setVipId(Integer vipId) {
		this.vipId = vipId;
	}

	public Date getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(Date joinTime) {
		this.joinTime = joinTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getFormatJoinTime() {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		return sdf.format(this.joinTime);
	}

	public void setFormatJoinTime(String formatJoinTime) {
		this.formatJoinTime = formatJoinTime;
	}

	public Set<Consume> getConsumes() {
		return consumes;
	}

	public void setConsumes(Set<Consume> consumes) {
		this.consumes = consumes;
	}

}
