package com.vipmanage.model;
// Generated 2016-8-19 17:54:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commodity generated by hbm2java
 */
@Entity
@Table(name = "commodity")
public class Commodity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer commodityId;
	private String commodityName;
	private BigDecimal price;
	private BigDecimal agio;

	public Commodity() {
	}

	public Commodity(String commodityName, BigDecimal price, BigDecimal agio) {
		this.commodityName = commodityName;
		this.price = price;
		this.agio = agio;
	}

	public Integer getCommodityId() {
		return this.commodityId;
	}

	public void setCommodityId(Integer commodityId) {
		this.commodityId = commodityId;
	}

	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	// 获取格式化后精确到毛的价格
	public BigDecimal getFormatPrice() {
		return this.price.setScale(1, BigDecimal.ROUND_HALF_UP);
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getAgio() {
		return this.agio;
	}

	public void setAgio(BigDecimal agio) {
		this.agio = agio;
	}

	// 获取整数类型的折扣
	public BigDecimal getFormatAgio() {
		return new BigDecimal(new Float(this.agio.floatValue() * 100).intValue());
	}
}
